# -*- coding: utf-8 -*-
"""密钥管理专项回归: 用户私有密钥 + 环境变量优先 + 禁止向上扫描 + fail-closed。"""
import os
import re

import pytest

from mca_core.patch_manager import integrity


@pytest.fixture(autouse=True)
def _isolate_key_env(monkeypatch, tmp_path):
    """隔离真实用户目录与部署环境变量。"""
    monkeypatch.delenv("MCA_PATCH_SECRET", raising=False)
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "xdg"))
    yield


def test_env_var_highest_priority(monkeypatch, tmp_path):
    monkeypatch.setenv("MCA_PATCH_SECRET", "env-secret")
    assert integrity.get_patch_key() == b"env-secret"


def test_legacy_key_in_fixed_cwd(tmp_path, monkeypatch):
    (tmp_path / ".patch_key").write_text("legacy-key-1\n")
    monkeypatch.chdir(tmp_path)
    assert integrity.get_patch_key() == b"legacy-key-1"


def test_user_key_autogenerated_and_persistent(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)  # cwd 无遗留密钥
    key1 = integrity.get_patch_key()
    assert key1 and re.fullmatch(r"[0-9a-f]{64}", key1.decode())
    key_file = tmp_path / "xdg" / "logbrain" / "patch.key"
    assert key_file.exists()
    if os.name == "posix":
        assert (key_file.stat().st_mode & 0o777) == 0o600
    key2 = integrity.get_patch_key()
    assert key1 == key2  # 持久化，二次调用不重新生成


def test_hijacked_parent_key_is_ignored(tmp_path, monkeypatch):
    """向上扫描已移除: 上层目录的 .patch_key 不得被读取。"""
    (tmp_path / ".patch_key").write_text("EVIL-KEY-FROM-PARENT\n")
    child = tmp_path / "child"
    child.mkdir()
    monkeypatch.chdir(child)
    key = integrity.get_patch_key()
    assert key != b"EVIL-KEY-FROM-PARENT"
    assert key and re.fullmatch(r"[0-9a-f]{64}", key.decode())  # 走用户密钥


def test_generation_failure_returns_none_fail_closed(tmp_path, monkeypatch):
    """密钥完全不可用时返回 None（调用方 fail-closed）。"""
    blocker = tmp_path / "not-a-dir"
    blocker.write_text("i am a file")
    monkeypatch.setenv("XDG_CONFIG_HOME", str(blocker))  # makedirs 将失败
    monkeypatch.chdir(tmp_path)
    assert integrity.get_patch_key() is None


def test_state_a_legacy_key_compat_with_signed_patch(tmp_path, monkeypatch):
    """有 .patch_key 状态: 项目自有签名补丁校验必须照常通过。"""
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.exists(os.path.join(project_root, ".patch_key")):
        pytest.skip("项目根无 .patch_key")
    monkeypatch.chdir(project_root)
    from mca_core.patch_manager import PatchManager

    pm = PatchManager(os.path.join(project_root, "patches"))
    pm.scan()
    ok, msg = pm.verify_integrity("hotfix_secure_ops")
    assert ok, msg
